FROM node:22.18.0

WORKDIR /app

ARG PORT=3333
ARG NODE_ENV
ARG DB_CLIENT
ARG DB_POOL_MIN
ARG DB_POOL_MAX
ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASS
ARG DB_DATABASE
ARG JWT_SECRET
ARG JWT_EXPIRES_IN
ARG SALT_RESULT
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_SECURITY
ARG MAIL_USER
ARG MAIL_PASS
ARG MAIL_FROM
ARG FRONTEND_URL

ENV PORT=$PORT
ENV NODE_ENV=$NODE_ENV
ENV DB_CLIENT=$DB_CLIENT
ENV DB_POOL_MIN=$DB_POOL_MIN
ENV DB_POOL_MAX=$DB_POOL_MAX
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV DB_DATABASE=$DB_DATABASE
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_EXPIRES_IN=$JWT_EXPIRES_IN
ENV SALT_RESULT=$SALT_RESULT
ENV MAIL_HOST=$MAIL_HOST
ENV MAIL_PORT=$MAIL_PORT
ENV MAIL_SECURITY=$MAIL_SECURITY
ENV MAIL_USER=$MAIL_USER
ENV MAIL_PASS=$MAIL_PASS
ENV MAIL_FROM=$MAIL_FROM
ENV FRONTEND_URL=$FRONTEND_URL

# Instalar rsync e NestJS CLI
RUN apt-get update && apt-get install -y rsync

COPY . .

RUN npm ci

RUN npm run build

EXPOSE $PORT

CMD ["npm", "start"]
